#!/usr/bin/pwsh
## Interactive script that writes a youtube-dl Script
## Requires an internet connection

# Setup
Clear-Host

# Preliminary archiving information
Write-Host -ForegroundColor Blue "Create Your Own Youtube-DL Script"
$arcdir = Read-Host -Prompt "Folder to archive channels in"
$exists = Test-Path -PathType Container $arcdir
If ($exists = "False") {MkDir $arcdir -ErrorAction SilentlyContinue -InformationAction Ignore} # mk arcdir if it doesn't exist
Set-Location $arcdir
# Check for ytdl
Write-Host ""
If ((Get-Command "youtube-dl" -ErrorAction SilentlyContinue) -eq $null) { # Check for ytdl
   Write-Host -ForegroundColor Red "Youtube-DL not found in your PATH or working directory." # if not found
   Write-Host 1: "Download Youtube-DL"
   Write-Host 2: "Exit Script"
   $choice = Read-Host -Prompt "(1 - 2)"
   If ( $choice = 1) {
     Write-Host -ForegroundColor Blue "Downloading Youtube-DL..."
     Invoke-WebRequest https://github.com/ytdl-org/youtube-dl/releases/download/2021.06.06/youtube-dl.exe -Outfile youtube-dl.exe # install it
     Write-Host -ForegroundColor Blue "Checking for updates..."
     youtube-dl --update # get latest version
   }
   Else {
     Write-Host "To add a folder to your PATH:"
     Write-Host "Settings > System > Info > Advanced system settings > Environment Variables... >"
     Write-Host "User variables > Path > New"
     Exit
   }
}
Else {Write-Host -ForegroundColor Green "Youtube-DL auto-detected."} # if found

# folder setup
Write-Host -ForegroundColor Blue "Writing config file..."
Write-Output '--format ("bestvideo[width>=1920]"/bestvideo)+bestaudio/best
--download-archive .\saved.db
--output %(uploader)s/%(title)s.%(id)s.%(ext)s
--restrict-filenames
--merge-output-format mkv
--ignore-errors
--console-title
--write-description
--write-thumbnail' >> .\dl.conf

Write-Host -ForegroundColor Blue "Creating archive list..."
New-Item saved.db

# Start writing the script
Write-Host -ForegroundColor Blue "Writing script header..."
Write-Output "#!/usr/bin/pwsh
## Youtube-DL Archiving Script
## Auto-Generated by Angelo's ins-arc.ps1
## Requires Youtube-DL and FFmpeg in your PATH
## This script can be moved anywhere without breakage

## Variables
`$archivedir = $arcdir # Archive folder
`$config = $arcdir.\config.ini # Config file
`$ogdir = Get-Location # Current folder

## Youtube Archive
# Go to archive folder
Set-Location $","archivedir" >> upg-arc.ps1

# Get channels
$chanlink = "-"
While ($chanlink -ne "") {
  $chanlink = Read-Host -Prompt "Enter channel link"
  $chantitle = Read-Host -Prompt "Enter channel name"
  Write-Host "#", chantitle >> upg-arc.ps1
  Write-Host -Separator "" "youtube-dl ",$chanlink," --config-location $","config" >> upg-arc.ps1
}

# Close off script
Write-Host '

## Final steps
# Add blank space
Write-Host ""
Write-Host ""
# Get folder size
Write-Host "Main archive size (gigabytes):",$([Math]::Round(((Get-ChildItem $archivedir -Recurse | Measure-Object -Property Length -Sum).Sum / 1GB),2))
# More blank space
Write-Host ""
Write-Host ""
# Return to original folder
Set-Location $ogdir' >> upg-arc.ps1
